### ISSUE TITLE
Add travis configuration

### ISSUE THREAD

**Issue by lmasello** [lmasello/Tp-Taller-de-Programacion-2-App-Server#9]
### Example
```
language: c
compiler: gcc
addons:
  apt:
    packages:
      - ...
before_script:
  - mkdir build
script:
  - cd build
  - cmake ../
  - make
  - make test
  - ./test
after_success:
  - lcov ...
```
